# Generated by Django 3.1.4 on 2020-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kenya',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
